id: P0F7B0B73
initial_creation_type: input
source_metadata:
  title: Dolpopa Sherab Gyaltsen
  language: en
  description: Texts by and about Dolpopa Sherab Gyaltsen (dol po pa shes rab rgyal
    mtshan, 1292–1361), who was one of the most influential masters in Tibetan history.
    He trained in the Sakya tradition and then moved to Jonang Monastery, where he
    established a formidable yet controversial scholarly tradition.
  volume:
    aad83ebe794940519a9757329ad569c3:
      title: 'An Envoy for Swiftly Invoking the Blessings of Definitive Meaning: Calling
        the Great Omniscient Jonangpa from Afar'
      parent: Calling the Guru from Afar
    ec7536b8da6c4bceb84a9e75f05edda7:
      title: Guru Sādhana of the Omniscient Dolpopa
      parent: Guru Yoga
    a90a757e5f0344e5a566f20c6c17207e:
      title: Aspiration Prayer of the Ultimate Definitive Meaning
      parent: Prayers
    374598dcd3af4aceab8b8dca54660f1e:
      title: In Praise of the Eight Siddhas
      parent: Prayers
created_at: '2022-02-28T23:02:01.164031'
last_modified_at: '2022-02-28T23:02:01.164037'
